/**
 * Zambian provinces, districts, and school types.
 * Used throughout registration, filtering, and reporting.
 */

export const PROVINCES = [
  'Central',
  'Copperbelt',
  'Eastern',
  'Luapula',
  'Lusaka',
  'Muchinga',
  'Northern',
  'North-Western',
  'Southern',
  'Western',
] as const;

export type Province = (typeof PROVINCES)[number];

export const DISTRICTS: Record<Province, string[]> = {
  Central: [
    'Chibombo',
    'Itezhi-Tezhi',
    'Kabwe',
    'Kapiri Mposhi',
    'Mkushi',
    'Mumbwa',
    'Ngabwe',
    'Serenje',
    'Shibuyunji',
  ],
  Copperbelt: [
    'Chililabombwe',
    'Chingola',
    'Kitwe',
    'Luanshya',
    'Lufwanyama',
    'Masaiti',
    'Mpongwe',
    'Mufulira',
    'Ndola',
  ],
  Eastern: [
    'Chadiza',
    'Chipangali',
    'Chipata',
    'Kasenengwa',
    'Katete',
    'Lundazi',
    'Mambwe',
    'Nyimba',
    'Petauke',
    'Sinda',
    'Vubwi',
  ],
  Luapula: [
    'Chembe',
    'Chienge',
    'Chipili',
    'Kawambwa',
    'Lunga',
    'Mansa',
    'Milenge',
    'Mwansabombwe',
    'Mwense',
    'Nchelenge',
    'Samfya',
  ],
  Lusaka: ['Chilanga', 'Chongwe', 'Kafue', 'Luangwa', 'Lusaka', 'Rufunsa'],
  Muchinga: [
    'Chama',
    'Chinsali',
    'Isoka',
    'Kanchibiya',
    'Lavushimanda',
    'Mpika',
    'Mafinga',
    'Nakonde',
    'Shiwangandu',
  ],
  Northern: ['Kasama', 'Kaputa', 'Luwingu', 'Mbala', 'Mporokoso', 'Mpulungu', 'Mungwi', 'Nsama'],
  'North-Western': [
    'Chavuma',
    'Ikelenge',
    'Kabompo',
    'Kalumbila',
    'Kasempa',
    'Manyinga',
    'Mufumbwe',
    'Mushindamo',
    'Mwinilunga',
    'Solwezi',
    'Zambezi',
  ],
  Southern: [
    'Chikankata',
    'Choma',
    'Gwembe',
    'Itezhi-Tezhi',
    'Kalomo',
    'Kazungula',
    'Livingstone',
    'Mazabuka',
    'Monze',
    'Namwala',
    'Pemba',
    'Siavonga',
    'Sinazongwe',
    'Zimba',
  ],
  Western: [
    'Kalabo',
    'Kaoma',
    'Limulunga',
    'Lukulu',
    'Mongu',
    'Mulobezi',
    'Mwandi',
    'Nalolo',
    'Nkeyema',
    'Senanga',
    'Sesheke',
    'Shangombo',
    'Sikongo',
    'Sioma',
  ],
};

export const SCHOOL_TYPES = [
  { value: 'day_primary', label: 'Day Primary School' },
  { value: 'day_secondary', label: 'Day Secondary School' },
  { value: 'boarding_primary', label: 'Boarding Primary School' },
  { value: 'boarding_secondary', label: 'Boarding Secondary School' },
  { value: 'mixed_secondary', label: 'Mixed Secondary (Day + Boarding)' },
  { value: 'college', label: 'College / Tertiary Institution' },
  { value: 'technical', label: 'Technical / Vocational School' },
] as const;

export type SchoolType = (typeof SCHOOL_TYPES)[number]['value'];
